mkvote: Run parse-rfd first and exit if it barfs mkcfv.pl: Only create the CFV message from the contents of the control files mkvote.pl: Becomes obsolete parse-rfd.pl: Do the hard work parsing the RFD and write control files
git-svn-id: http://svn.local.tull.net/svn/ausadmin-base/trunk@150 8ab3fd6c-811f-0410-acb7-fe4950304a8b

diff --git a/bin/mkvote b/bin/mkvote
--- a/bin/mkvote
+++ b/bin/mkvote
@@ -49,9 +49,19 @@ echo "14" > $Newsgroup/voteperiod
 echo `date +%s` > $Newsgroup/posted.cfg
 perl -e 'print $^T,"\n"' > $Newsgroup/starttime.cfg
 
-# Run the Perl script mkcvf to make the CFV and PGP-sign it then post it away!
-tr -d '\r' < $HomeDir/tmp/info.$$ | mkcfv.pl > $Newsgroup/posted.cfv 2>$HomeDir/tmp/pgp.$$
-S=$?
+# Save the RFD
+tr -d '\r' < $HomeDir/tmp/info.$$ > $Newsgroup/rfd
+# And create all the config files
+parse-rfd.pl < $Newsgroup/rfd
+s=$?
+if [ $s != 0 ] ; then
+	echo "Unable to parse the RFD -- code $s - fatal"
+	exit 6
+fi
+
+# Run the Perl script mkcfv to make the CFV and PGP-sign it then post it away!
+mkcfv.pl < $Newsgroup/rfd > $Newsgroup/posted.cfv 2>$HomeDir/tmp/pgp.$$
+s=$?
 if [ $s != 0 ] ; then
 	echo "Unable to make Call For Votes -- code $s - fatal"
 	cat $Newsgroup/posted.cfv 2>$HomeDir/tmp/pgp.$$
